services:
  ak-automated-uploader:
    image: ghcr.io/golitedev/ak-automated-uploader:latest
    container_name: ak-automated-uploader
    user: "1001:10"

    environment:
      TZ: America/Asuncion
      ORIGIN: http://192.168.18.29:51901
      AK_MEDIA_ROOTS: /hdd1,/hdd2,/hdd3,/hdd4

    volumes:
      - /volume2/docker/ak-automated-uploader/config:/config
      - /volume1/hdd1:/hdd1:ro
      - /volume3/hdd2:/hdd2:ro
      - /volume4/hdd3:/hdd3:ro
      - /volume5/hdd4:/hdd4:ro

    ports:
      - "51901:51901"

    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
